name: CI MLflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CSV_URL: "Project/wine-quality.csv"
  TARGET_VAR: "quality"
  ALPHA: 0.5
  L1_RATIO: 0.5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print environment variables
        run: |
          echo "CSV_URL=$CSV_URL"
          echo "TARGET_VAR=$TARGET_VAR"
          echo "ALPHA=$ALPHA"
          echo "L1_RATIO=$L1_RATIO"
